import { Prisma } from '@prisma/client';

export const parkingPassListSelect = Prisma.validator<Prisma.ParkingPassSelect>()({
  id: true,
  status: true,
  duration: true,
  startTime: true,
  endTime: true,
  visitorName: true,
  visitorPhone: true,
  visitorEmail: true,
  passType: true,
  confirmationCode: true,
  createdAt: true,
  vehicle: {
    select: {
      id: true,
      licensePlate: true,
      make: true,
      model: true,
      year: true,
      color: true,
      state: true,
      isBlacklisted: true,
      violationCount: true,
      riskScore: true,
    },
  },
  unit: {
    select: {
      id: true,
      unitNumber: true,
      floor: true,
      section: true,
      building: {
        select: {
          id: true,
          name: true,
          slug: true,
          address: true,
          timezone: true,
        },
      },
    },
  },
  parkingZone: {
    select: {
      id: true,
      name: true,
      code: true,
      description: true,
    },
  },
});

export const parkingPassDetailsSelect = Prisma.validator<Prisma.ParkingPassSelect>()({
  ...parkingPassListSelect,
  isInOutEnabled: true,
  lastExitTime: true,
  lastEntryTime: true,
  reactivatedAt: true,
  isEmergency: true,
  priorityLevel: true,
  isRecurring: true,
  recurringEndDate: true,
  parentPassId: true,
  registeredVia: true,
  createdByResidentId: true,
  confirmationSent: true,
  confirmationSentAt: true,
  expirationWarningSent: true,
  smsNotificationSent: true,
  requiresApproval: true,
  approvedBy: true,
  approvedAt: true,
  approvalNotes: true,
  viewCount: true,
  lastViewedAt: true,
  deletedAt: true,
  deletedBy: true,
  deletionReason: true,
  updatedAt: true,
});
